- hosts: nomad_client
  roles:
    - role: common
      common_hostname: "{{ inventory_hostname }}"
      common_apt_packages: [
        "jq",
        "net-tools",
        "unzip",
      ]

    - role: hashicorp_release
      hashicorp_release_product_name: "nomad"
      hashicorp_release_product_version: "1.10.0"
      hashicorp_release_product_checksum: "sha256:b542daaeaf9ddd9f109bbf1a4ec1c05d6b6f2d3645c0ebe21786dec8b447e7d6"

    - role: gantsign.golang
      golang_gopath: "/home/{{ ansible_user_id }}/go"
      golang_version: "1.24.1"
      golang_redis_sha256sum: "8df5750ffc0281017fb6070fba450f5d22b600a02081dceef47966ffaf36a3af"

    - role: cni

    - role: "geerlingguy.docker"
      become: true
      docker_users:
        - "{{ ansible_user_id }}"

    - role: tls
      tls_self_signed_generate:
        - agent-name: "{{ inventory_hostname }}"
          ip: "{{ ansible_facts['default_ipv4']['address'] }}"
          dns: "client.lcy1.nomad"

    - role: helper
      helper_apt_packages:
        - "build-essential"
        - "git"
        - "make"
      helper_file_write_content:
        - content: "bridge"
          dst: "/etc/modules-load.d/nomad.conf"
      helper_file_write_template:
        - src: "./templates/nomad_client.hcl.j2"
          dst: "/etc/nomad.d/client.hcl"
      helper_file_copy_local:
        - src: "./files/nomad.service"
          dst: "/etc/systemd/system/nomad.service"
        - src: "./.tls/ca-certificate.pem"
          dst: "/etc/nomad.d/.tls/ca.crt"
        - src: "./.tls/{{ inventory_hostname }}-certificate.pem"
          dst: "/etc/nomad.d/.tls/nomad.crt"
        - src: "./.tls/{{ inventory_hostname }}-certificate.key"
          dst: "/etc/nomad.d/.tls/nomad.key"
      helper_systemd_start_service_name: "nomad"
