- hosts: nomad_server
  roles:
    - role: common
      common_hostname: "{{ inventory_hostname }}"
      common_apt_packages: [
        "jq",
        "net-tools",
        "unzip",
      ]

    - role: hashicorp_release
      hashicorp_release_product_name: "nomad"
      hashicorp_release_product_version: "1.9.6"

    - role: gantsign.golang
      golang_gopath: "/home/{{ ansible_user_id }}/go"
      golang_version: "1.23.6"
      golang_redis_sha256sum: "561c780e8f4a8955d32bf72e46af0b5ee5e0debe1e4633df9a03781878219202"

    - role: helper
      helper_apt_packages:
        - "build-essential"
        - "git"
        - "make"
      helper_file_write_template:
        - src: "./templates/nomad_server.hcl.j2"
          dst: "/etc/nomad.d/server.hcl"
      helper_file_copy_local:
        - src: "./files/nomad.service"
          dst: "/etc/systemd/system/nomad.service"
      helper_file_write_content_local:
        - content: "b6e63b6a-527c-14db-9474-063cb1dcc026\n"
          dst: "{{ playbook_dir }}/generated_nomad_root_bootstrap_token"
      helper_systemd_start_service_name: "nomad"
