- ansible.builtin.include_vars: "./defaults/acl.yaml"

- name: "create_acl_config_file"
  become: true
  ansible.builtin.template:
    src: "acl.hcl.j2"
    dest: "{{ nomad_config_dir }}/acl.hcl"
    owner: "{{ nomad_user }}"
    group: "{{ nomad_group }}"
    mode: "0655"
  when: nomad_acl_enabled is true
  notify:
    - "restart_nomad"
