- name: "install_binary"
  ansible.builtin.copy:
    remote_src: yes
    src: "{{ nomad_binary_path }}"
    dest: "/usr/local/bin/"
    owner: "{{ nomad_user }}"
    group: "{{ nomad_group }}"
    mode: "0777"
  become: true
  notify:
    - "restart_nomad"

- name: "create_service_file"
  become: true
  ansible.builtin.template:
    src: "nomad.service.j2"
    dest: "/etc/systemd/system/nomad.service"
    owner: "root"
    group: "root"
    mode: "0755"
  notify:
    - "reload_systemd"
