- name: "install_nvme_packages"
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: "present"
    update_cache: true
  loop: "{{ virt_nvme_apt_packages }}"

- name: "install_virt_packages"
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: "present"
    update_cache: true
  loop: "{{ virt_libvirt_apt_packages }}"
  notify:
    - "reload_systemd"
    - "restart_libvirtd"
