- hosts: nomad_server
  roles:
    - role: common
      common_hostname: "{{ inventory_hostname }}"
      common_apt_packages: [
        "jq",
        "net-tools",
        "unzip",
      ]

    - role: gantsign.golang
      golang_gopath: "/home/{{ ansible_user_id }}/go"
      golang_version: "1.23.6"
      golang_redis_sha256sum: "561c780e8f4a8955d32bf72e46af0b5ee5e0debe1e4633df9a03781878219202"

    - role: helper
      helper_apt_packages:
        - "build-essential"
        - "git"
        - "make"
      helper_file_write_template:
        - src: "./templates/nomad_server.hcl.j2"
          dst: "/home/{{ ansible_user_id }}/nomad-server.hcl"
          owner: "{{ ansible_user_id }}"
          group: "{{ ansible_user_id }}"
