ceph_version: 18.2.2

ceph_cephadm_install_dir: "/usr/bin"
ceph_cephadm_install_method: "none"
ceph_cephadm_download_url: "https://download.ceph.com/rpm-{{ ceph_version }}/el9/noarch/cephadm"

ceph_cephadm_bootstrap: false
ceph_cephadm_bootstrap_args: [ ]
ceph_cephadm_bootstrap_hosts: [ ]
ceph_cephadm_bootstrap_mons: [ ]
ceph_cephadm_bootstrap_mgrs: [ ]
ceph_cephadm_bootstrap_osd_hosts: [ ]
ceph_cephadm_bootstrap_osd_paths: [ ]

ceph_nvmeof_bootstrap: false
ceph_nvmeof_bootstrap_container_image: "quay.io/ceph/nvmeof:1.0.0"
ceph_nvmeof_bootstrap_pool_name: "default_0"
ceph_nvmeof_orch_service_name: "nvmeof.{{ ceph_nvmeof_bootstrap_pool_name }}"
ceph_nvmeof_bootstrap_placement_hosts: [ ]

ceph_nvmeof_cli_container_image: "quay.io/ceph/nvmeof-cli:1.0.0"
