- hosts: workstation
  roles:
    - role: common
      common_hostname: "workstation-0"

    - role: gantsign.golang
      golang_gopath: "/home/{{ ansible_user_id }}/go"
      golang_version: "1.23.4"
      golang_redis_sha256sum: "6924efde5de86fe277676e929dc9917d466efa02fb934197bc2eba35d5680971"

    - role: cni

    - role: "geerlingguy.docker"
      become: true
      docker_users:
        - "{{ ansible_user_id }}"

    - role: helper
      helper_apt_packages:
        - "build-essential"
        - "git"
        - "make"
