- name: "check_ceph_orch_list"
  ansible.builtin.command: "cephadm shell -- ceph orch ls --format json-pretty"
  register: ceph_orch_list
  become: true
  changed_when: false
  failed_when: false

- block:
    - name: "write_nvmeof_bootstrap_script"
      ansible.builtin.template:
        src: cephadm_nvmeof_setup.sh.j2
        dest: /tmp/cephadm_nvmeof_setup.sh
        owner: "root"
        group: "root"
        mode: "0744"
      become: true
    - name: "run_nvmeof_bootstrap_script"
      ansible.builtin.command: "/tmp/cephadm_nvmeof_setup.sh"
      become: yes
      register: nvmeof_bootstrap_cmd
  when:
    - "ceph_orch_list is not defined or ceph_nvmeof_orch_service_name|string not in ceph_orch_list.stdout"

- name: "write_nvmeof_subsystem_create_script"
  ansible.builtin.template:
    src: nvmeof_subsystem_create.sh.j2
    dest: /tmp/nvmeof_subsystem_create.sh
    owner: "root"
    group: "root"
    mode: "0744"
  become: true
