# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "bento/ubuntu-18.04"

  config.vm.synced_folder "#{Dir.home}/go/src/github.com/hashicorp/nomad", "/opt/gopath/src/github.com/hashicorp/nomad"

  config.vm.provision "shell" do |s|
    ssh_pub_key = File.readlines("#{Dir.home}/.ssh/donkey_id_rsa.pub").first.strip
    s.inline = <<-SHELL
      echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
      mkdir -p /donkey
      chown vagrant:vagrant /donkey
    SHELL
  end

  (1..1).each do |i|
    config.vm.define "eu-west-2-server-#{i}", autostart: false do |node|
      node.vm.hostname = "eu-west-2-server-#{i}"
      node.vm.network "private_network", ip: "192.168.60.#{i}0"

      node.vm.provider "virtualbox" do |vb|
        vb.memory = 2048
        vb.cpus = 4
      end
    end
  end

  (1..2).each do |i|
    config.vm.define "eu-west-2-client-#{i}", autostart: false do |node|
      node.vm.hostname = "eu-west-2-client-#{i}"
      node.vm.network "private_network", ip: "192.168.70.#{i}0"

      node.vm.provider "virtualbox" do |vb|
        vb.memory = 1024
        vb.cpus = 1
      end
    end
  end

  (1..1).each do |i|
    config.vm.define "eu-central-1-server-#{i}", autostart: false do |node|
      node.vm.hostname = "eu-central-1-server-#{i}"
      node.vm.network "private_network", ip: "192.168.160.#{i}0"

      node.vm.provider "virtualbox" do |vb|
        vb.memory = 2048
        vb.cpus = 4
      end
    end
  end

  (1..2).each do |i|
    config.vm.define "eu-central-1-client-#{i}", autostart: false do |node|
      node.vm.hostname = "eu-central-1-client-#{i}"
      node.vm.network "private_network", ip: "192.168.170.#{i}0"

      node.vm.provider "virtualbox" do |vb|
        vb.memory = 1024
        vb.cpus = 1
      end
    end
  end
end
