# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "bento/ubuntu-18.04"

  config.vm.synced_folder "../nomad", "/opt/gopath/src/github.com/hashicorp/nomad"

  (1..1).each do |i|
    config.vm.define "eu-west-1-server-#{i}" do |node|
      node.vm.hostname = "eu-west-1-server-#{i}"
      node.vm.network "private_network", ip: "192.168.60.#{i}0"

      node.vm.provider "virtualbox" do |vb|
        vb.memory = 2048
        vb.cpus = 4
      end
    end
  end

  (1..2).each do |i|
    config.vm.define "eu-west-1-client-#{i}" do |node|
      node.vm.hostname = "eu-west-1-client-#{i}"
      node.vm.network "private_network", ip: "192.168.70.#{i}0"

      node.vm.provider "virtualbox" do |vb|
        vb.memory = 1024
        vb.cpus = 1
      end
    end
  end

  (1..1).each do |i|
    config.vm.define "eu-west-2-server-#{i}" do |node|
      node.vm.hostname = "eu-west-2-server-#{i}"
      node.vm.network "private_network", ip: "192.168.160.#{i}0"

      node.vm.provider "virtualbox" do |vb|
        vb.memory = 2048
        vb.cpus = 4
      end
    end
  end

  (1..2).each do |i|
    config.vm.define "eu-west-2-client-#{i}" do |node|
      node.vm.hostname = "eu-west-2-client-#{i}"
      node.vm.network "private_network", ip: "192.168.170.#{i}0"

      node.vm.provider "virtualbox" do |vb|
        vb.memory = 1024
        vb.cpus = 1
      end
    end
  end
end
