module "ca" {
  source = "../../shared/terraform/tls"

  local_path = "${path.root}/.tls"
  ca_create  = true
}

module "hashi-ctrl" {
  source = "../../shared/terraform/multipass-compute"

  ansible_group_name   = "hashi_ctrl"
  instance_count       = 3
  instance_cpus        = 2
  instance_memory      = "4GiB"
  instance_name_prefix = "hashi-ctrl"
  instance_ssh_key     = file("~/.ssh/id_rsa.pub")
}

module "hashi-dtpl" {
  source = "../../shared/terraform/multipass-compute"

  ansible_group_name   = "hashi_dtpl"
  instance_count       = 2
  instance_memory      = "4GiB"
  instance_name_prefix = "hashi-dtpl"
  instance_ssh_key     = file("~/.ssh/id_rsa.pub")
}

module "ansible_provision" {
  source     = "../../shared/terraform/ansible-provision"
  depends_on = [module.ca, module.hashi-ctrl, module.hashi-dtpl]

  ansible_inventory_path = abspath("./inventory.yaml")
  ansible_playbook_path  = abspath("./playbook_all.yaml")
}

# Read the Vault init output generated by the Ansible bootstrap, so we can use
# the root token to configure the Nomad workload identity integration.
data "local_file" "vault_init" {
  depends_on = [module.ansible_provision]
  filename   = "${path.root}/generated_vault_init.json"
}

provider "vault" {
  address      = "https://${module.hashi-ctrl.instance_ips[0]}:8200"
  ca_cert_file = "${path.root}/.tls/ca.pem"
  token        = jsondecode(data.local_file.vault_init.content).root_token
}

module "vault_nomad_wi" {
  source     = "../../shared/terraform/hashicorp-vault-nomad-wi"
  depends_on = [module.ansible_provision, terraform_data.cleanup]

  nomad_address     = "https://${module.hashi-ctrl.instance_ips[0]}:4646"
  nomad_jwks_ca_pem = module.ca.ca_cert_pem
  vault_kv_mount    = "nomad-lcy1"

  providers = {
    vault = vault
  }
}


# Cleanup generated files on destroy, so these do not pile up over multiple runs
# and cause confusion.
resource "terraform_data" "cleanup" {
  provisioner "local-exec" {
    when    = destroy
    command = "rm -rf ${path.root}/.tls ${path.root}/.envrc ${path.root}/generated_vault_init.json"
  }
}

output "msg" {
  value = <<EOH
SSH commands:
  HashiStack Control Plane:
%{for ip in module.hashi-ctrl.instance_ips~}
    - ssh ${ip}
%{endfor~}
  HashiStack Data Plane:
%{for ip in module.hashi-dtpl.instance_ips~}
    - ssh ${ip}
%{endfor~}

Nomad UI:   https://${module.hashi-ctrl.instance_ips[0]}:4646
Vault UI:   https://${module.hashi-ctrl.instance_ips[0]}:8200
Consul UI:  https://${module.hashi-ctrl.instance_ips[0]}:8501
EOH
}
