- hosts: workstation
  roles:
    - role: common
      common_hostname: "event-horizon"
      common_apt_packages: [
        "jq",
        "net-tools",
        "unzip",
      ]

    - role: gantsign.golang
      golang_gopath: "/home/{{ ansible_user_id }}/go"
      golang_version: "1.23.6"
      golang_redis_sha256sum: "561c780e8f4a8955d32bf72e46af0b5ee5e0debe1e4633df9a03781878219202"

    - role: cni

    - role: "geerlingguy.docker"
      become: true
      docker_users:
        - "{{ ansible_user_id }}"

    - role: helper
      helper_apt_packages:
        - "build-essential"
        - "git"
        - "make"
