- hosts: nomad_server

  # Variables that need to be changed, depending on who is running the playbook.
  vars:
    github_email: "2980562+jrasell@users.noreply.github.com"
    ssh_key_private_filename: "id_rsa"
    ssh_key_public_filename: "id_rsa.pub"

  roles:
    - role: common
      common_hostname: "nomad-server-0"

    - role: hashicorp_release
      hashicorp_release_product_name: "vault"
      hashicorp_release_product_version: "1.18.0"

    - role: gantsign.golang
      golang_gopath: "{{ ansible_user_dir }}/go"
      golang_version: "1.23.2"
      golang_redis_sha256sum: "542d3c1705f1c6a1c5a80d5dc62e2e45171af291e755d591c5e6531ef63b454e"

    - role: helper
      helper_apt_packages:
        - "build-essential"
        - "git"
        - "make"
      helper_file_write_template:
        - src: "./templates/nomad_server.hcl.j2"
          dst: "{{ ansible_user_dir }}/nomad_server.hcl"
          owner: "{{ ansible_user_id }}"
          group: "{{ ansible_user_id }}"
        - src: "./templates/nomad_vault.hcl.j2"
          dst: "{{ ansible_user_dir }}/nomad_vault.hcl"
          owner: "{{ ansible_user_id }}"
          group: "{{ ansible_user_id }}"
      helper_file_write_content:
        - content: "b6e63b6a-527c-14db-9474-063cb1dcc026"
          dst: "{{ ansible_user_dir }}/root_bootstrap_token"
          owner: "{{ ansible_user_id }}"
          group: "{{ ansible_user_id }}"
        - content: |
            [user]
              email = {{ github_email }}
            [url "ssh://git@github.com/"]
              insteadOf = https://github.com/
          dst: "{{ ansible_user_dir }}//.gitconfig"
          owner: "{{ ansible_user_id }}"
          group: "{{ ansible_user_id }}"
      helper_file_copy_local:
        - src: "{{ hostvars['localhost']['ansible_user_dir'] }}/.ssh/{{ ssh_key_private_filename }}"
          dst: "{{ ansible_user_dir }}/.ssh/id_rsa"
          owner: "{{ ansible_user_id }}"
          group: "{{ ansible_user_id }}"
          mode: "600"
        - src: "{{ hostvars['localhost']['ansible_user_dir'] }}/.ssh/{{ ssh_key_public_filename }}"
          dst: "{{ ansible_user_dir }}/.ssh/id_rsa.pub"
          owner: "{{ ansible_user_id }}"
          group: "{{ ansible_user_id }}"
          mode: "600"

  tasks:
    - name: "add_github_ssh_keys"
      ansible.builtin.shell: "ssh-keyscan github.com >> {{ ansible_user_dir }}/.ssh/known_hosts"
