- hosts: nomad_client
  roles:
    - role: common
      common_hostname: "nomad-client-0"

    - role: gantsign.golang
      golang_gopath: "/home/{{ ansible_user_id }}/go"
      golang_version: "1.23.2"
      golang_redis_sha256sum: "542d3c1705f1c6a1c5a80d5dc62e2e45171af291e755d591c5e6531ef63b454e"

    - role: cni

    - role: "geerlingguy.docker"
      become: true

    - role: helper
      helper_apt_packages:
        - "build-essential"
        - "git"
        - "make"
      helper_file_write_template:
        - src: "./templates/nomad_client.hcl.j2"
          dst: "/home/{{ ansible_user_id }}/nomad_client.hcl"
        - src: "./templates/nomad_vault.hcl.j2"
          dst: "/home/{{ ansible_user_id }}/nomad_vault.hcl"
