- hosts: libvirt
  roles:
    - role: common
      common_hostname: "libvirt-0"

    - role: virt

    - role: gantsign.golang
      golang_gopath: "/home/{{ ansible_user_id }}/go"
      golang_version: "1.23.1"
      golang_redis_sha256sum: "49bbb517cfa9eee677e1e7897f7cf9cfdbcf49e05f61984a2789136de359f9bd"

    - role: helper
      helper_apt_packages: [
        "build-essential",
        "git",
        "libvirt-dev",
        "make",
      ]
      helper_sync_local_paths: [ "{{ ansible_user_dir }}/Projects/Go/nomad-driver-virt" ]
