[[language]]
name        = "go"
auto-format = true
formatter   = { command = "goimports" }

[[language]]
name = "hcl"
auto-format = true
formatter = { command = "hclfmt", args = [] }

[[langauge]]
name = "rust"

[language-server.rust-analyzer.config.check]
command = "clippy"
