- hosts: virt
  roles:
    - role: virt
      nvme_connect_fabrics_tcp: [
        { "address": '{{ hostvars[ "ceph_0" ][ "ansible_default_ipv4" ][ "address" ] }}',
          "port": 4420,
          "subsystem": "nqn.2016-06.io.spdk:vm",
        }
      ]

    - role: gantsign.golang
      golang_gopath: "/home/jrasell/go"
      golang_version: "1.22.5"
      golang_redis_sha256sum: "904b924d435eaea086515bc63235b192ea441bd8c9b198c507e85009e6e4c7f0"

    - role: helper
      helper_apt_packages: [
        "build-essential",
        "git",
        "libvirt-dev",
        "make",
      ]
      helper_sync_local_paths: [ "/Users/jrasell/Projects/Go/sync-1" ]
