- name: "download_prometheus_node_exporter"
  get_url:
    url: "{{ prometheus_node_exporter_url }}"
    dest: "/tmp/prometheus_node_exporter.tar.gz"
    timeout: "60"
    mode: '600'
  become: false

- name: "download_and_unarchive_prometheus_node_exporter"
  become: true
  ansible.builtin.unarchive:
    src: "{{ prometheus_node_exporter_url }}"
    dest: "/tmp"
    mode: "0755"
    remote_src: true

- name: "move_prometheus_node_exporter_binary"
  become: true
  copy:
    src: "/tmp/{{ prometheus_node_exporter_tar_file }}/node_exporter"
    dest: "{{ prometheus_node_exporter_install_dir }}/"
    mode: 0755
    remote_src: true
  notify:
    - "restart_prometheus_node_exporter"

- name: "remove_prometheus_node_exporter_archive"
  become: true
  ansible.builtin.file:
    path: "/tmp/{{ prometheus_node_exporter_tar_file }}"
    state: "absent"

- name: "create_prometheus_node_exporter_service_file"
  become: true
  ansible.builtin.template:
    src: "prometheus_node_exporter.service.j2"
    dest: "/etc/systemd/system/prometheus_node_exporter.service"
    owner: "root"
    group: "root"
    mode: "0755"
  notify:
    - "reload_systemd"
