- hosts: util
  roles:
    - role: gantsign.golang
      golang_gopath: "/home/jrasell/go"
      golang_version: "1.22.4"
      golang_redis_sha256sum: "a8e177c354d2e4a1b61020aca3562e27ea3e8f8247eca3170e3fa1e0c2f9e771"
    - role: common
    - role: build
