- name: "restart_libvirtd"
  become: true
  ansible.builtin.service:
    name: "libvirtd"
    state: "restarted"

- name: "reload_systemd"
  become: true
  ansible.builtin.systemd:
    daemon_reexec: true
