- hosts: localhost
  connection: local

- hosts: workstation

  # Variables that need to be changed, depending on who is running the playbook.
  vars:
    github_email: "2980562+jrasell@users.noreply.github.com"
    ssh_key_private_filename: "id_rsa"
    ssh_key_public_filename: "id_rsa.pub"

  roles:
    - role: common
      common_hostname: "workstation-0"

    - role: gantsign.golang
      golang_gopath: "{{ ansible_user_dir }}/go"
      golang_version: "1.24.1"
      golang_redis_sha256sum: "cb2396bae64183cdccf81a9a6df0aea3bce9511fc21469fb89a0c00470088073"

    - role: cni

    - role: "geerlingguy.docker"
      become: true
      docker_users:
        - "{{ ansible_user_id }}"

    - role: helper
      helper_apt_packages:
        - "build-essential"
        - "git"
        - "make"
      helper_file_copy_local:
        - src: "{{ hostvars['localhost']['ansible_user_dir'] }}/.ssh/{{ ssh_key_private_filename }}"
          dst: "{{ ansible_user_dir }}/.ssh/id_rsa"
          owner: "{{ ansible_user_id }}"
          group: "{{ ansible_user_id }}"
          mode: "600"
        - src: "{{ hostvars['localhost']['ansible_user_dir'] }}/.ssh/{{ ssh_key_public_filename }}"
          dst: "{{ ansible_user_dir }}/.ssh/id_rsa.pub"
          owner: "{{ ansible_user_id }}"
          group: "{{ ansible_user_id }}"
          mode: "600"
      helper_file_write_content:
        - content: |
            [user]
              email = {{ github_email }}
            [url "ssh://git@github.com/"]
              insteadOf = https://github.com/
          dst: "{{ ansible_user_dir }}//.gitconfig"
          owner: "{{ ansible_user_id }}"
          group: "{{ ansible_user_id }}"

  tasks:
    - name: "add_github_ssh_keys"
      ansible.builtin.shell: "ssh-keyscan github.com >> {{ ansible_user_dir }}/.ssh/known_hosts"
