- name: "file_copy_local"
  include_tasks: "file_copy_local.yaml"
  with_items: "{{ helper_file_copy_local }}"

- name: "file_write_template"
  include_tasks: "file_write_template.yaml"
  with_items: "{{ helper_file_write_template }}"

- name: "file_write_content"
  include_tasks: "file_write_content.yaml"
  with_items: "{{ helper_file_write_content }}"

- name: "file_write_content_local"
  ansible.builtin.copy:
    content: "{{ item['content'] }}"
    dest: "{{ item['dst'] }}"
  with_items: "{{ helper_file_write_content_local }}"
  delegate_to: 127.0.0.1
  run_once: true
