- name: "file_copy_local_stat_dir"
  stat:
    path: "{{ item.dst | dirname }}"
  register: dir_stat

- name: "file_copy_local_ensure_dir"
  become: true
  file:
    path: "{{ item.dst | dirname }}"
    state: directory
    owner: "{{ item['owner'] | default('root') }}"
    group: "{{ item['group'] | default('root') }}"
    mode: "{{ item['mode'] | default('0755') }}"
  when: not dir_stat.stat.exists

- name: "file_copy_local"
  become: true
  ansible.builtin.copy:
    src: "{{ item['src'] }}"
    dest: "{{ item['dst'] }}"
    owner: "{{ item['owner'] | default('root') }}"
    group: "{{ item['group'] | default('root') }}"
    mode: "{{ item['mode'] | default('0755') }}"
