- name: "restart_nomad"
  become: true
  ansible.builtin.systemd_service:
    name: "nomad"
    state: "restarted"

- name: "enable_nomad"
  become: true
  ansible.builtin.systemd_service:
    name: "nomad"
    enabled: true
    masked: no

- name: "reload_systemd"
  become: true
  ansible.builtin.systemd:
    daemon_reexec: true
