- name: "check_local_envrc_file_exists"
  stat:
    path: "{{ (nomad_cli_direnv_path, '.envrc') | path_join }}"
  register: envrc_stat
  delegate_to: localhost

- name: "write_local_envrc_file"
  ansible.builtin.template:
    src: "envrc.j2"
    dest: "{{ (nomad_cli_direnv_path, '.envrc') | path_join }}"
    mode: "0755"
  delegate_to: localhost
  when: nomad_cli_direnv_path is defined and not envrc_stat.stat.exists
  run_once: true
