- name: "create_tls_directory"
  become: true
  ansible.builtin.file:
    path: "{{ nomad_config_dir }}/tls"
    owner: "{{ nomad_user }}"
    group: "{{ nomad_group }}"
    state: "directory"
    mode: "0711"

- name: "write_tls_files"
  become: true
  ansible.builtin.copy:
    dest: "{{ item.dest }}"
    src: "{{ item.src }}"
    owner: "{{ nomad_user }}"
    group: "{{ nomad_group }}"
    mode: "0644"
  when: nomad_tls_enabled is true
  loop:
    - dest: "{{ nomad_config_dir }}/tls/ca.pem"
      src: "{{ nomad_tls_ca_cert }}"
    - dest: "{{ nomad_config_dir }}/tls/cert.pem"
      src: "{{ nomad_tls_cert }}"
    - dest: "{{ nomad_config_dir }}/tls/cert-key.pem"
      src: "{{ nomad_tls_cert_key }}"

- name: "create_tls_config_file"
  become: true
  ansible.builtin.template:
    src: "tls.hcl.j2"
    dest: "{{ nomad_config_dir }}/tls.hcl"
    owner: "{{ nomad_user }}"
    group: "{{ nomad_group }}"
    mode: "0655"
  when: nomad_tls_enabled is true
  notify:
    - "restart_nomad"
