- name: "check_timedatectl_ntpd"
  become: true
  ansible.builtin.command: "timedatectl"
  register: timedatectl_ntpd_status

- name: "disable_timedatectl_ntp"
  become: true
  ansible.builtin.command: "timedatectl set-ntp no"
  when: '"NTP service: active" in timedatectl_ntpd_status.stdout'

- name: "install_packages"
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: "present"
    update_cache: true
  loop: "{{ common_apt_packages }}"

- ansible.builtin.include_tasks: "debian_motd.yaml"
  when: ansible_distribution == "Ubuntu"

- name: "set_hostname"
  become: true
  ansible.builtin.hostname:
    name: "{{ common_hostname }}"
    use: systemd
  when: common_hostname is defined

- name: "create_groups"
  become: true
  ansible.builtin.group:
    name: "{{ item.name }}"
    state: present
  with_items: "{{ common_users }}"

- name: "create_users"
  become: true
  ansible.builtin.user:
    name: "{{ item.name }}"
    group: "{{ item.name }}"
    groups: "adm,cdrom,sudo,dip,lxd"
    shell: "/bin/bash"
  with_items: "{{ common_users }}"

- name: "set_authorized_keys"
  become: true
  ansible.posix.authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "{{ item.ssh_key }}"
  with_items: "{{ common_users }}"

- name: "create_sudoers"
  become: true
  community.general.sudoers:
    name: "{{ item.name }}"
    state: present
    user: "{{ item.name }}"
    commands: ALL
  with_items: "{{ common_users }}"
