- name: "restart_{{ nomad_service_name }}"
  become: true
  ansible.builtin.systemd_service:
    name: "{{ nomad_service_name }}"
    state: "restarted"

- name: "enable_{{ nomad_service_name }}"
  become: true
  ansible.builtin.systemd_service:
    name: "{{ nomad_service_name }}"
    enabled: true
    masked: no

- name: "reload_systemd"
  become: true
  ansible.builtin.systemd:
    daemon_reexec: true
